name: general_test
on:
  push:

jobs:
  general_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm ci --no-audit

      - name: Build Package
        run: npm run lib:build

      - name: Link Package
        run: npm run lib:link

      - name: ESLinting
        run: npm run lint

      - name: Testing
        run: npm run test -- --coverage --watchAll=false

      - name: General Build
        run: npm run build

      - name: Storybook Build
        run: npm run build-storybook
