name: node_versions_test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  node_version_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-audit --cache .npm --prefer-offline --silent

      - name: Test Coverage
        run: npm run test -- --coverage --watchAll=false
