name: storybook_deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  storybook_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci --no-audit

      - name: Build Package
        run: npm run lib:build

      - name: Link Package
        run: npm run lib:link

      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
